### PR TITLE
Minor README Updates

### PR DESCRIPTION
**Pull request by mrxinu**

### CODE REVIEW

**Review by shawndwells — APPROVED** [review]
Thanks for helping clean these up @mrxinu !

**Comment by mrxinu** [comment]
My pleasure @shawndwells! Did you have any thoughts on the question above about the target OS and target path?

**Comment by shawndwells** [comment]
@mrxinu not seeing a question --

image

**Comment by mrxinu** [comment]
Oh, sorry, new'ish to reviews on GH if you can believe it. It's in a review request.

image

**Pull request merged**
